// Country name to ISO 3166-1 alpha-2 code mapping for flag images
export const countryCodeMap: Record<string, string> = {
  'Belgium': 'be',
  'Czech Republic': 'cz',
  'England': 'gb-eng',
  'Wales': 'gb-wls',
  'Scotland': 'gb-sct',
  'Northern Ireland': 'gb-nir',
  'Ireland': 'ie',
  'France': 'fr',
  'Germany': 'de',
  'Spain': 'es',
  'Italy': 'it',
  'Portugal': 'pt',
  'Netherlands': 'nl',
  'Poland': 'pl',
  'Croatia': 'hr',
  'Serbia': 'rs',
  'Brazil': 'br',
  'Argentina': 'ar',
  'Uruguay': 'uy',
  'Colombia': 'co',
  'Mexico': 'mx',
  'USA': 'us',
  'Canada': 'ca',
  'Japan': 'jp',
  'South Korea': 'kr',
  'Australia': 'au',
  'Nigeria': 'ng',
  'Ghana': 'gh',
  'Senegal': 'sn',
  'Cameroon': 'cm',
  'Morocco': 'ma',
  'Egypt': 'eg',
  'Algeria': 'dz',
  'South Africa': 'za',
  'Cape Verde': 'cv',
  'Turkey': 'tr',
  'Ukraine': 'ua',
  'Sweden': 'se',
  'Norway': 'no',
  'Denmark': 'dk',
  'Switzerland': 'ch',
  'Austria': 'at',
  'Greece': 'gr',
  'Russia': 'ru',
};

export const getCountryFlagUrl = (country: string): string => {
  const code = countryCodeMap[country] || 'un';
  return `https://flagcdn.com/w40/${code}.png`;
};
