// Country name to ISO 3166-1 alpha-2 code mapping for flag images
export const countryCodeMap: Record<string, string> = {
  'Albania': 'al',
  'Algeria': 'dz',
  'Argentina': 'ar',
  'Australia': 'au',
  'Austria': 'at',
  'Belgium': 'be',
  'Bosnian': 'ba',
  'Brazil': 'br',
  'Cameroon': 'cm',
  'Canada': 'ca',
  'Canadian': 'ca',
  'Cape Verde': 'cv',
  'Cape Verdean': 'cv',
  'Chad': 'td',
  'Colombia': 'co',
  'Croatia': 'hr',
  'Czech Republic': 'cz',
  'Denmark': 'dk',
  'DRC': 'cd',
  'Egypt': 'eg',
  'England': 'gb-eng',
  'English': 'gb-eng',
  'France': 'fr',
  'Germany': 'de',
  'Ghana': 'gh',
  'Greece': 'gr',
  'Greek': 'gr',
  'Ireland': 'ie',
  'Italy': 'it',
  'Ivory Coast': 'ci',
  'Japan': 'jp',
  'Kosovo': 'xk',
  'Latvia': 'lv',
  'Latvian': 'lv',
  'Mexico': 'mx',
  'Morocco': 'ma',
  'Netherlands': 'nl',
  'Nigeria': 'ng',
  'Nigerian': 'ng',
  'North Macedonia': 'mk',
  'North Macedonian': 'mk',
  'Northern Ireland': 'gb-nir',
  'Norway': 'no',
  'Poland': 'pl',
  'Portugal': 'pt',
  'Romania': 'ro',
  'Russia': 'ru',
  'Scotland': 'gb-sct',
  'Senegal': 'sn',
  'Serbia': 'rs',
  'Sierra Leone': 'sl',
  'Slovakia': 'sk',
  'South Africa': 'za',
  'South Korea': 'kr',
  'Spain': 'es',
  'Sweden': 'se',
  'Switzerland': 'ch',
  'Turkey': 'tr',
  'Ukraine': 'ua',
  'Uruguay': 'uy',
  'USA': 'us',
  'Wales': 'gb-wls',
};

export const getCountryFlagUrl = (country: string): string => {
  const code = countryCodeMap[country] || 'un';
  return `https://flagcdn.com/w40/${code}.png`;
};
