// Country name to flag emoji mapping
export const countryFlags: Record<string, string> = {
  'Belgium': '🇧🇪',
  'Czech Republic': '🇨🇿',
  'England': '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
  'Wales': '🏴󠁧󠁢󠁷󠁬󠁳󠁿',
  'Scotland': '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
  'Northern Ireland': '🇬🇧',
  'Ireland': '🇮🇪',
  'France': '🇫🇷',
  'Germany': '🇩🇪',
  'Spain': '🇪🇸',
  'Italy': '🇮🇹',
  'Portugal': '🇵🇹',
  'Netherlands': '🇳🇱',
  'Poland': '🇵🇱',
  'Croatia': '🇭🇷',
  'Serbia': '🇷🇸',
  'Brazil': '🇧🇷',
  'Argentina': '🇦🇷',
  'Uruguay': '🇺🇾',
  'Colombia': '🇨🇴',
  'Mexico': '🇲🇽',
  'USA': '🇺🇸',
  'Canada': '🇨🇦',
  'Japan': '🇯🇵',
  'South Korea': '🇰🇷',
  'Australia': '🇦🇺',
  'Nigeria': '🇳🇬',
  'Ghana': '🇬🇭',
  'Senegal': '🇸🇳',
  'Cameroon': '🇨🇲',
  'Morocco': '🇲🇦',
  'Egypt': '🇪🇬',
  'Algeria': '🇩🇿',
  'South Africa': '🇿🇦',
  'Turkey': '🇹🇷',
  'Ukraine': '🇺🇦',
  'Sweden': '🇸🇪',
  'Norway': '🇳🇴',
  'Denmark': '🇩🇰',
  'Switzerland': '🇨🇭',
  'Austria': '🇦🇹',
  'Greece': '🇬🇷',
  'Russia': '🇷🇺',
};

export const getCountryFlag = (country: string): string => {
  return countryFlags[country] || '🌍';
};
