// Hardcoded club positions that match the europe-outline.gif map
// These are the visual x/y coordinates on the 1000x600 SVG viewbox

export interface HardcodedClubPosition {
  name: string;
  country: string;
  x: number;
  y: number;
}

export const hardcodedClubPositions: HardcodedClubPosition[] = [
  // Czech Republic clubs
  { name: "Bohemians 1905", country: "Czech Republic", x: 465, y: 405 },
  { name: "FC Vysočina Jihlava", country: "Czech Republic", x: 475, y: 415 },
  { name: "TJ Jiskra Domažlice", country: "Czech Republic", x: 455, y: 410 },
  // England clubs
  { name: "Norwich City FC", country: "England", x: 345, y: 365 },
  { name: "Forest Green Rovers", country: "England", x: 315, y: 380 },
  { name: "Arsenal FC", country: "England", x: 335, y: 385 },
  { name: "Chelsea FC", country: "England", x: 332, y: 386 },
  { name: "Fulham FC", country: "England", x: 333, y: 387 },
  { name: "Brentford FC", country: "England", x: 334, y: 384 },
  { name: "Crystal Palace", country: "England", x: 336, y: 388 },
  { name: "Tottenham Hotspur", country: "England", x: 337, y: 383 },
  { name: "West Ham United", country: "England", x: 338, y: 386 },
  { name: "Brighton & Hove Albion", country: "England", x: 335, y: 393 },
  { name: "AFC Bournemouth", country: "England", x: 318, y: 390 },
  { name: "Aston Villa", country: "England", x: 318, y: 375 },
  { name: "Wolverhampton Wanderers", country: "England", x: 315, y: 372 },
  { name: "Nottingham Forest", country: "England", x: 325, y: 370 },
  { name: "Liverpool FC", country: "England", x: 312, y: 365 },
  { name: "Everton FC", country: "England", x: 313, y: 367 },
  { name: "Manchester City", country: "England", x: 316, y: 363 },
  { name: "Manchester United", country: "England", x: 317, y: 364 },
  { name: "Leeds United", country: "England", x: 322, y: 358 },
  { name: "Burnley FC", country: "England", x: 320, y: 360 },
  { name: "Newcastle United", country: "England", x: 322, y: 345 },
  { name: "Sunderland AFC", country: "England", x: 324, y: 343 },
  // France clubs
  { name: "LOSC Lille", country: "France", x: 360, y: 390 },
  { name: "Le Havre AC", country: "France", x: 345, y: 410 },
  { name: "FC Metz", country: "France", x: 385, y: 415 },
  { name: "AJ Auxerre", country: "France", x: 365, y: 435 },
  { name: "FC Nantes", country: "France", x: 335, y: 440 },
  { name: "Angers SCO", country: "France", x: 340, y: 435 },
  { name: "FC Lorient", country: "France", x: 325, y: 445 },
  { name: "FC Toulouse", country: "France", x: 350, y: 485 },
  { name: "AS Monaco", country: "France", x: 400, y: 485 },
  { name: "OGC Nice", country: "France", x: 395, y: 490 },
  { name: "Stade Rennais FC", country: "France", x: 332, y: 425 },
  { name: "Stade Brestois 29", country: "France", x: 320, y: 425 },
  { name: "Paris Saint-Germain", country: "France", x: 358, y: 420 },
  { name: "Paris FC", country: "France", x: 359, y: 421 },
  { name: "RC Lens", country: "France", x: 362, y: 395 },
  { name: "RC Strasbourg Alsace", country: "France", x: 395, y: 425 },
  { name: "Olympique Lyon", country: "France", x: 378, y: 455 },
  { name: "Olympique Marseille", country: "France", x: 378, y: 495 },
  // Germany clubs
  { name: "1. FC Union Berlin", country: "Germany", x: 480, y: 355 },
  { name: "Borussia Dortmund", country: "Germany", x: 405, y: 375 },
  { name: "Borussia Mönchengladbach", country: "Germany", x: 393, y: 380 },
  { name: "1. FC Köln", country: "Germany", x: 395, y: 385 },
  { name: "Bayer 04 Leverkusen", country: "Germany", x: 398, y: 387 },
  { name: "1. FSV Mainz 05", country: "Germany", x: 405, y: 405 },
  { name: "Eintracht Frankfurt", country: "Germany", x: 410, y: 405 },
  { name: "1. FC Heidenheim 1846", country: "Germany", x: 420, y: 415 },
  { name: "FC Augsburg", country: "Germany", x: 430, y: 425 },
  { name: "Bayern Munich", country: "Germany", x: 435, y: 425 },
  { name: "VfB Stuttgart", country: "Germany", x: 415, y: 420 },
  { name: "SC Freiburg", country: "Germany", x: 405, y: 430 },
  { name: "TSG 1899 Hoffenheim", country: "Germany", x: 413, y: 412 },
  { name: "VfL Wolfsburg", country: "Germany", x: 430, y: 355 },
  { name: "SV Werder Bremen", country: "Germany", x: 415, y: 345 },
  { name: "Hamburger SV", country: "Germany", x: 425, y: 335 },
  { name: "FC St. Pauli", country: "Germany", x: 426, y: 336 },
  { name: "RB Leipzig", country: "Germany", x: 455, y: 375 },
  // Spain clubs
  { name: "Celta de Vigo", country: "Spain", x: 270, y: 500 },
  { name: "Athletic Bilbao", country: "Spain", x: 300, y: 495 },
  { name: "Deportivo Alavés", country: "Spain", x: 305, y: 495 },
  { name: "CA Osasuna", country: "Spain", x: 310, y: 500 },
  { name: "Atlético de Madrid", country: "Spain", x: 310, y: 520 },
  { name: "Getafe CF", country: "Spain", x: 311, y: 521 },
  { name: "FC Barcelona", country: "Spain", x: 360, y: 515 },
  { name: "Girona FC", country: "Spain", x: 365, y: 505 },
  { name: "Levante UD", country: "Spain", x: 335, y: 535 },
  { name: "Elche CF", country: "Spain", x: 330, y: 540 },
  { name: "Real Madrid", country: "Spain", x: 310, y: 520 },
  { name: "Rayo Vallecano", country: "Spain", x: 312, y: 519 },
  { name: "Real Sociedad", country: "Spain", x: 308, y: 493 },
  { name: "Real Oviedo", country: "Spain", x: 278, y: 493 },
  { name: "Sevilla FC", country: "Spain", x: 290, y: 555 },
  { name: "Real Betis Balompié", country: "Spain", x: 291, y: 556 },
  { name: "Valencia CF", country: "Spain", x: 334, y: 536 },
  { name: "Villarreal CF", country: "Spain", x: 337, y: 532 },
  { name: "RCD Espanyol Barcelona", country: "Spain", x: 361, y: 516 },
  { name: "RCD Mallorca", country: "Spain", x: 365, y: 540 },
  // Italy clubs
  { name: "Inter Milan", country: "Italy", x: 445, y: 455 },
  { name: "AC Milan", country: "Italy", x: 446, y: 456 },
  { name: "Como 1907", country: "Italy", x: 442, y: 452 },
  { name: "Atalanta BC", country: "Italy", x: 448, y: 453 },
  { name: "Hellas Verona", country: "Italy", x: 455, y: 455 },
  { name: "Genoa CFC", country: "Italy", x: 425, y: 475 },
  { name: "Bologna FC 1909", country: "Italy", x: 450, y: 475 },
  { name: "ACF Fiorentina", country: "Italy", x: 450, y: 490 },
  { name: "AS Roma", country: "Italy", x: 465, y: 515 },
  { name: "Cagliari Calcio", country: "Italy", x: 425, y: 530 },
  { name: "Juventus FC", country: "Italy", x: 405, y: 455 },
  { name: "Torino FC", country: "Italy", x: 406, y: 456 },
  { name: "Udinese Calcio", country: "Italy", x: 480, y: 450 },
  { name: "Parma Calcio 1913", country: "Italy", x: 440, y: 470 },
  { name: "US Sassuolo", country: "Italy", x: 445, y: 472 },
  { name: "US Cremonese", country: "Italy", x: 448, y: 457 },
  { name: "Pisa Sporting Club", country: "Italy", x: 440, y: 490 },
  { name: "SS Lazio", country: "Italy", x: 466, y: 516 },
  { name: "SSC Napoli", country: "Italy", x: 470, y: 525 },
  { name: "US Lecce", country: "Italy", x: 510, y: 530 },
  // Ukraine
  { name: "Dynamo Kyiv", country: "Ukraine", x: 635, y: 405 },
  { name: "Obolon Kyiv", country: "Ukraine", x: 636, y: 406 },
  { name: "Shakhtar Donetsk", country: "Ukraine", x: 700, y: 440 },
  { name: "Zorya Lugansk", country: "Ukraine", x: 720, y: 430 },
  { name: "Metalist 1925 Kharkiv", country: "Ukraine", x: 680, y: 410 },
  { name: "Rukh Lviv", country: "Ukraine", x: 560, y: 410 },
  { name: "Karpaty Lviv", country: "Ukraine", x: 561, y: 411 },
  { name: "Kryvbas Kryvyi Rig", country: "Ukraine", x: 650, y: 440 },
  { name: "LNZ Cherkasy", country: "Ukraine", x: 640, y: 420 },
  { name: "NK Veres Rivne", country: "Ukraine", x: 580, y: 395 },
  { name: "Polissya Zhytomyr", country: "Ukraine", x: 610, y: 400 },
  { name: "SC Poltava", country: "Ukraine", x: 665, y: 415 },
  { name: "Epicentr Kamyanets-Podilskyi", country: "Ukraine", x: 585, y: 430 },
  { name: "Kolos Kovalivka", country: "Ukraine", x: 630, y: 410 },
  { name: "FC Oleksandriya", country: "Ukraine", x: 645, y: 430 },
  { name: "FC Kudrivka", country: "Ukraine", x: 632, y: 408 },
  // Portugal
  { name: "FC Porto", country: "Portugal", x: 235, y: 518 },
  { name: "FC Arouca", country: "Portugal", x: 238, y: 522 },
  { name: "FC Famalicão", country: "Portugal", x: 238, y: 515 },
  { name: "FC Alverca", country: "Portugal", x: 235, y: 535 },
  { name: "SC Braga", country: "Portugal", x: 237, y: 515 },
  { name: "SL Benfica", country: "Portugal", x: 235, y: 536 },
  { name: "Sporting CP", country: "Portugal", x: 236, y: 537 },
  { name: "Vitória Guimarães SC", country: "Portugal", x: 238, y: 516 },
  { name: "AVS Futebol", country: "Portugal", x: 237, y: 517 },
  { name: "Casa Pia AC", country: "Portugal", x: 236, y: 536 },
  { name: "CD Nacional", country: "Portugal", x: 200, y: 560 },
  { name: "CD Santa Clara", country: "Portugal", x: 150, y: 535 },
  { name: "CD Tondela", country: "Portugal", x: 232, y: 525 },
  { name: "CF Estrela Amadora", country: "Portugal", x: 236, y: 535 },
  { name: "GD Estoril Praia", country: "Portugal", x: 234, y: 536 },
  { name: "Gil Vicente FC", country: "Portugal", x: 237, y: 516 },
  { name: "Moreirense FC", country: "Portugal", x: 237, y: 517 },
  { name: "Rio Ave FC", country: "Portugal", x: 236, y: 517 },
  // Romania
  { name: "CFR Cluj", country: "Romania", x: 565, y: 450 },
  { name: "CS Universitatea Craiova", country: "Romania", x: 560, y: 485 },
  { name: "FC Botosani", country: "Romania", x: 585, y: 440 },
  { name: "ACSC FC Arges", country: "Romania", x: 565, y: 475 },
  { name: "AFC Unirea 04 Slobozia", country: "Romania", x: 590, y: 480 },
  { name: "AFK Csikszereda Miercurea Ciuc", country: "Romania", x: 575, y: 450 },
  { name: "FC Universitatea Cluj", country: "Romania", x: 566, y: 451 },
  { name: "FCSB", country: "Romania", x: 580, y: 485 },
  { name: "FCV Farul Constanta", country: "Romania", x: 600, y: 485 },
  { name: "Petrolul Ploiesti", country: "Romania", x: 580, y: 475 },
  { name: "SC Otelul Galati", country: "Romania", x: 600, y: 455 },
  { name: "UTA Arad", country: "Romania", x: 540, y: 455 },
  { name: "FC Dinamo 1948", country: "Romania", x: 581, y: 486 },
  { name: "FC Hermannstadt", country: "Romania", x: 565, y: 460 },
  { name: "FC Metaloglobus Bucharest", country: "Romania", x: 580, y: 484 },
  { name: "FC Rapid 1923", country: "Romania", x: 581, y: 485 },
  // Russia
  { name: "CSKA Moscow", country: "Russia", x: 695, y: 345 },
  { name: "Dynamo Moscow", country: "Russia", x: 696, y: 346 },
  { name: "FC Krasnodar", country: "Russia", x: 720, y: 455 },
  { name: "FC Rostov", country: "Russia", x: 710, y: 440 },
  { name: "FC Sochi", country: "Russia", x: 730, y: 470 },
  { name: "Akhmat Grozny", country: "Russia", x: 750, y: 470 },
  { name: "Akron Togliatti", country: "Russia", x: 785, y: 380 },
  { name: "Baltika Kaliningrad", country: "Russia", x: 540, y: 370 },
  { name: "Dinamo Makhachkala", country: "Russia", x: 750, y: 465 },
  { name: "FC Pari Nizhniy Novgorod", country: "Russia", x: 730, y: 350 },
  { name: "Zenit St. Petersburg", country: "Russia", x: 635, y: 315 },
  { name: "Krylya Sovetov Samara", country: "Russia", x: 800, y: 380 },
  { name: "Lokomotiv Moscow", country: "Russia", x: 697, y: 347 },
  { name: "Rubin Kazan", country: "Russia", x: 780, y: 350 },
  { name: "Spartak Moscow", country: "Russia", x: 695, y: 346 },
  { name: "Torpedo Moscow", country: "Russia", x: 696, y: 345 },
  // Scotland
  { name: "Celtic FC", country: "Scotland", x: 280, y: 312 },
  { name: "Rangers FC", country: "Scotland", x: 281, y: 313 },
  { name: "Aberdeen FC", country: "Scotland", x: 288, y: 305 },
  { name: "Dundee FC", country: "Scotland", x: 288, y: 310 },
  { name: "Dundee United FC", country: "Scotland", x: 289, y: 311 },
  { name: "Motherwell FC", country: "Scotland", x: 282, y: 313 },
  { name: "St. Mirren FC", country: "Scotland", x: 279, y: 313 },
  { name: "Falkirk FC", country: "Scotland", x: 284, y: 314 },
  { name: "Heart of Midlothian FC", country: "Scotland", x: 286, y: 315 },
  { name: "Hibernian FC", country: "Scotland", x: 287, y: 316 },
  { name: "Kilmarnock FC", country: "Scotland", x: 280, y: 314 },
  { name: "Livingston FC", country: "Scotland", x: 285, y: 314 },
  // Serbia
  { name: "FK IMT Belgrad", country: "Serbia", x: 525, y: 485 },
  { name: "FK Cukaricki", country: "Serbia", x: 526, y: 486 },
  { name: "FK Partizan Belgrade", country: "Serbia", x: 527, y: 487 },
  { name: "Red Star Belgrade", country: "Serbia", x: 528, y: 488 },
  { name: "OFK Beograd", country: "Serbia", x: 529, y: 489 },
  { name: "FK Vojvodina Novi Sad", country: "Serbia", x: 522, y: 471 },
  { name: "Zeleznicar Pancevo", country: "Serbia", x: 530, y: 480 },
  { name: "FK Radnik Surdulica", country: "Serbia", x: 538, y: 500 },
  { name: "FK Spartak Subotica", country: "Serbia", x: 520, y: 468 },
  { name: "FK TSC Backa Topola", country: "Serbia", x: 521, y: 469 },
  { name: "FK Javor-Matis Ivanjica", country: "Serbia", x: 518, y: 490 },
  { name: "FK Mladost Lucani", country: "Serbia", x: 522, y: 486 },
  { name: "FK Napredak Krusevac", country: "Serbia", x: 530, y: 490 },
  { name: "FK Novi Pazar", country: "Serbia", x: 518, y: 495 },
  { name: "FK Radnicki 1923 Kragujevac", country: "Serbia", x: 524, y: 488 },
  { name: "FK Radnicki Nis", country: "Serbia", x: 532, y: 494 },
  // Sweden
  { name: "AIK", country: "Sweden", x: 430, y: 280 },
  { name: "Djurgårdens IF", country: "Sweden", x: 431, y: 281 },
  { name: "Hammarby IF", country: "Sweden", x: 432, y: 282 },
  { name: "IF Brommapojkarna", country: "Sweden", x: 433, y: 283 },
  { name: "BK Häcken", country: "Sweden", x: 395, y: 300 },
  { name: "GAIS", country: "Sweden", x: 396, y: 301 },
  { name: "IFK Göteborg", country: "Sweden", x: 397, y: 302 },
  { name: "IF Elfsborg", country: "Sweden", x: 398, y: 305 },
  { name: "Halmstads BK", country: "Sweden", x: 398, y: 315 },
  { name: "Degerfors IF", country: "Sweden", x: 410, y: 290 },
  { name: "IFK Norrköping", country: "Sweden", x: 422, y: 295 },
  { name: "IK Sirius", country: "Sweden", x: 425, y: 285 },
  { name: "Malmö FF", country: "Sweden", x: 398, y: 325 },
  { name: "Mjällby AIF", country: "Sweden", x: 412, y: 320 },
  { name: "IFK Värnamo", country: "Sweden", x: 408, y: 308 },
  { name: "Östers IF", country: "Sweden", x: 415, y: 315 },
  // Switzerland
  { name: "FC Zürich", country: "Switzerland", x: 402, y: 440 },
  { name: "Grasshopper Club Zürich", country: "Switzerland", x: 403, y: 441 },
  { name: "FC Winterthur", country: "Switzerland", x: 404, y: 438 },
  { name: "BSC Young Boys", country: "Switzerland", x: 395, y: 445 },
  { name: "FC Thun", country: "Switzerland", x: 395, y: 455 },
  { name: "FC Basel 1893", country: "Switzerland", x: 385, y: 440 },
  { name: "FC Luzern", country: "Switzerland", x: 398, y: 448 },
  { name: "FC Lausanne-Sport", country: "Switzerland", x: 388, y: 455 },
  { name: "Servette FC", country: "Switzerland", x: 386, y: 460 },
  { name: "FC Sion", country: "Switzerland", x: 390, y: 465 },
  { name: "FC St. Gallen 1879", country: "Switzerland", x: 412, y: 438 },
  { name: "FC Lugano", country: "Switzerland", x: 405, y: 470 },
  // Turkey
  { name: "Fenerbahçe", country: "Turkey", x: 635, y: 545 },
  { name: "Beşiktaş JK", country: "Turkey", x: 636, y: 546 },
  { name: "Galatasaray", country: "Turkey", x: 637, y: 547 },
  { name: "Başakşehir FK", country: "Turkey", x: 638, y: 548 },
  { name: "Eyüpspor", country: "Turkey", x: 639, y: 549 },
  { name: "Kasımpaşa", country: "Turkey", x: 640, y: 550 },
  { name: "Fatih Karagümrük", country: "Turkey", x: 641, y: 551 },
  { name: "Alanyaspor", country: "Turkey", x: 655, y: 565 },
  { name: "Antalyaspor", country: "Turkey", x: 650, y: 565 },
  { name: "Çaykur Rizespor", country: "Turkey", x: 710, y: 545 },
  { name: "Trabzonspor", country: "Turkey", x: 700, y: 545 },
  { name: "Samsunspor", country: "Turkey", x: 680, y: 540 },
  { name: "Gaziantep FK", country: "Turkey", x: 685, y: 565 },
  { name: "Gençlerbirliği Ankara", country: "Turkey", x: 655, y: 535 },
  { name: "Göztepe", country: "Turkey", x: 605, y: 560 },
  { name: "Kayserispor", country: "Turkey", x: 670, y: 555 },
  { name: "Kocaelispor", country: "Turkey", x: 642, y: 540 },
  { name: "Konyaspor", country: "Turkey", x: 655, y: 560 },
  // Netherlands
  { name: "Ajax Amsterdam", country: "Netherlands", x: 378, y: 355 },
  { name: "FC Volendam", country: "Netherlands", x: 380, y: 352 },
  { name: "AZ Alkmaar", country: "Netherlands", x: 377, y: 350 },
  { name: "SC Telstar", country: "Netherlands", x: 376, y: 353 },
  { name: "Feyenoord Rotterdam", country: "Netherlands", x: 372, y: 364 },
  { name: "Excelsior Rotterdam", country: "Netherlands", x: 373, y: 365 },
  { name: "Sparta Rotterdam", country: "Netherlands", x: 374, y: 366 },
  { name: "FC Utrecht", country: "Netherlands", x: 380, y: 360 },
  { name: "FC Groningen", country: "Netherlands", x: 388, y: 335 },
  { name: "SC Heerenveen", country: "Netherlands", x: 383, y: 340 },
  { name: "Heracles Almelo", country: "Netherlands", x: 388, y: 352 },
  { name: "FC Twente", country: "Netherlands", x: 390, y: 355 },
  { name: "Go Ahead Eagles", country: "Netherlands", x: 386, y: 355 },
  { name: "PEC Zwolle", country: "Netherlands", x: 385, y: 350 },
  { name: "NEC Nijmegen", country: "Netherlands", x: 383, y: 368 },
  { name: "PSV Eindhoven", country: "Netherlands", x: 378, y: 375 },
  { name: "NAC Breda", country: "Netherlands", x: 375, y: 370 },
  { name: "Fortuna Sittard", country: "Netherlands", x: 370, y: 375 },
  // Norway
  { name: "FK Bodø/Glimt", country: "Norway", x: 420, y: 190 },
  { name: "Tromsø IL", country: "Norway", x: 445, y: 160 },
  { name: "Rosenborg BK", country: "Norway", x: 410, y: 230 },
  { name: "Molde FK", country: "Norway", x: 390, y: 240 },
  { name: "Kristiansund BK", country: "Norway", x: 385, y: 238 },
  { name: "SK Brann", country: "Norway", x: 360, y: 260 },
  { name: "FK Haugesund", country: "Norway", x: 355, y: 270 },
  { name: "Viking FK", country: "Norway", x: 350, y: 280 },
  { name: "Bryne FK", country: "Norway", x: 355, y: 285 },
  { name: "Sandefjord Fotball", country: "Norway", x: 410, y: 275 },
  { name: "Sarpsborg 08 FF", country: "Norway", x: 415, y: 275 },
  { name: "Fredrikstad FK", country: "Norway", x: 415, y: 278 },
  { name: "Strømsgodset IF", country: "Norway", x: 408, y: 272 },
  { name: "KFUM-Kameratene Oslo", country: "Norway", x: 412, y: 270 },
  { name: "Vålerenga Fotball", country: "Norway", x: 413, y: 271 },
  { name: "Hamarkameratene", country: "Norway", x: 418, y: 260 },
  // Poland
  { name: "Arka Gdynia", country: "Poland", x: 465, y: 340 },
  { name: "Jagiellonia Białystok", country: "Poland", x: 540, y: 345 },
  { name: "Lechia Gdańsk", country: "Poland", x: 467, y: 338 },
  { name: "Legia Warszawa", country: "Poland", x: 510, y: 362 },
  { name: "Radomiak Radom", country: "Poland", x: 515, y: 370 },
  { name: "Motor Lublin", country: "Poland", x: 545, y: 375 },
  { name: "Widzew Łódź", country: "Poland", x: 500, y: 370 },
  { name: "Korona Kielce", country: "Poland", x: 515, y: 385 },
  { name: "Raków Częstochowa", country: "Poland", x: 505, y: 390 },
  { name: "Cracovia", country: "Poland", x: 520, y: 405 },
  { name: "Bruk-Bet Termalica Nieciecza", country: "Poland", x: 528, y: 410 },
  { name: "GKS Katowice", country: "Poland", x: 515, y: 400 },
  { name: "Górnik Zabrze", country: "Poland", x: 512, y: 398 },
  { name: "Piast Gliwice", country: "Poland", x: 513, y: 395 },
  { name: "Pogoń Szczecin", country: "Poland", x: 440, y: 345 },
  { name: "Lech Poznań", country: "Poland", x: 470, y: 365 },
  { name: "Zagłębie Lubin", country: "Poland", x: 475, y: 375 },
  { name: "Wisła Płock", country: "Poland", x: 505, y: 360 },
  // Austria
  { name: "SK Sturm Graz", country: "Austria", x: 455, y: 420 },
  { name: "Grazer AK", country: "Austria", x: 456, y: 421 },
  { name: "Wolfsberger AC", country: "Austria", x: 445, y: 425 },
  { name: "TSV Hartberg", country: "Austria", x: 460, y: 423 },
  { name: "Austria Wien", country: "Austria", x: 480, y: 410 },
  { name: "FC Blau-Weiss Linz", country: "Austria", x: 445, y: 410 },
  { name: "WSG Tirol", country: "Austria", x: 415, y: 425 },
  { name: "SV Ried", country: "Austria", x: 435, y: 413 },
  { name: "Red Bull Salzburg", country: "Austria", x: 430, y: 415 },
  { name: "SCR Altach", country: "Austria", x: 420, y: 420 },
  // Belgium
  { name: "Club Brugge KV", country: "Belgium", x: 360, y: 375 },
  { name: "Cercle Brugge", country: "Belgium", x: 361, y: 376 },
  { name: "KAA Gent", country: "Belgium", x: 365, y: 378 },
  { name: "Oud-Heverlee Leuven", country: "Belgium", x: 370, y: 380 },
  { name: "KV Mechelen", country: "Belgium", x: 372, y: 382 },
  { name: "KVC Westerlo", country: "Belgium", x: 375, y: 384 },
  { name: "KRC Genk", country: "Belgium", x: 380, y: 385 },
  { name: "FCV Dender EH", country: "Belgium", x: 368, y: 382 },
  { name: "Royal Antwerp FC", country: "Belgium", x: 373, y: 378 },
  { name: "RSC Anderlecht", country: "Belgium", x: 371, y: 380 },
  { name: "Union Saint-Gilloise", country: "Belgium", x: 372, y: 381 },
  { name: "Standard Liège", country: "Belgium", x: 382, y: 383 },
  { name: "Royal Charleroi SC", country: "Belgium", x: 374, y: 383 },
  { name: "Sint-Truidense VV", country: "Belgium", x: 378, y: 382 },
  { name: "Zulte Waregem", country: "Belgium", x: 364, y: 380 },
  { name: "RAAL La Louvière", country: "Belgium", x: 370, y: 383 },
  // Bulgaria
  { name: "Arda Kardzhali", country: "Bulgaria", x: 550, y: 450 },
  { name: "Beroe Stara Zagora", country: "Bulgaria", x: 545, y: 445 },
  { name: "Botev Plovdiv", country: "Bulgaria", x: 544, y: 446 },
  { name: "Lokomotiv Plovdiv", country: "Bulgaria", x: 545, y: 447 },
  { name: "CSKA Sofia", country: "Bulgaria", x: 535, y: 445 },
  { name: "CSKA 1948", country: "Bulgaria", x: 536, y: 446 },
  { name: "Levski Sofia", country: "Bulgaria", x: 537, y: 447 },
  { name: "Lokomotiv Sofia", country: "Bulgaria", x: 538, y: 448 },
  { name: "Septemvri Sofia", country: "Bulgaria", x: 539, y: 449 },
  { name: "Slavia Sofia", country: "Bulgaria", x: 540, y: 450 },
  { name: "Cherno More Varna", country: "Bulgaria", x: 555, y: 440 },
  { name: "Spartak Varna", country: "Bulgaria", x: 556, y: 441 },
  { name: "Ludogorets Razgrad", country: "Bulgaria", x: 552, y: 438 },
  { name: "Botev Vratsa", country: "Bulgaria", x: 540, y: 440 },
  { name: "Dobrudzha Dobrich", country: "Bulgaria", x: 557, y: 437 },
  { name: "Montana", country: "Bulgaria", x: 532, y: 440 },
  // Croatia
  { name: "GNK Dinamo Zagreb", country: "Croatia", x: 470, y: 410 },
  { name: "HNK Gorica", country: "Croatia", x: 471, y: 411 },
  { name: "NK Lokomotiva Zagreb", country: "Croatia", x: 472, y: 412 },
  { name: "HNK Hajduk Split", country: "Croatia", x: 465, y: 440 },
  { name: "HNK Rijeka", country: "Croatia", x: 455, y: 415 },
  { name: "NK Istra 1961", country: "Croatia", x: 450, y: 420 },
  { name: "HNK Vukovar 1991", country: "Croatia", x: 500, y: 415 },
  // Denmark
  { name: "FC Copenhagen", country: "Denmark", x: 420, y: 315 },
  { name: "Brøndby IF", country: "Denmark", x: 421, y: 316 },
  { name: "FC Nordsjælland", country: "Denmark", x: 422, y: 314 },
  { name: "FC Midtjylland", country: "Denmark", x: 395, y: 320 },
  { name: "Silkeborg IF", country: "Denmark", x: 398, y: 322 },
  { name: "Aarhus GF", country: "Denmark", x: 405, y: 323 },
  { name: "Randers FC", country: "Denmark", x: 408, y: 321 },
  { name: "Odense Boldklub", country: "Denmark", x: 405, y: 330 },
  { name: "SønderjyskE", country: "Denmark", x: 395, y: 333 },
  { name: "FC Fredericia", country: "Denmark", x: 398, y: 332 },
  { name: "Viborg FF", country: "Denmark", x: 400, y: 323 },
  { name: "Vejle Boldklub", country: "Denmark", x: 402, y: 329 },
  // Greece
  { name: "AEK Athens", country: "Greece", x: 540, y: 475 },
  { name: "AE Kifisias", country: "Greece", x: 541, y: 476 },
  { name: "Panathinaikos FC", country: "Greece", x: 542, y: 477 },
  { name: "Atromitos Athens", country: "Greece", x: 543, y: 478 },
  { name: "Olympiacos Piraeus", country: "Greece", x: 544, y: 475 },
  { name: "APO Levadiakos", country: "Greece", x: 535, y: 473 },
  { name: "AE Larisa", country: "Greece", x: 530, y: 468 },
  { name: "Volos NPS", country: "Greece", x: 532, y: 467 },
  { name: "PAOK Thessaloniki", country: "Greece", x: 525, y: 460 },
  { name: "Aris Thessaloniki", country: "Greece", x: 526, y: 461 },
  { name: "Panserraikos", country: "Greece", x: 528, y: 458 },
  { name: "Asteras Aktor", country: "Greece", x: 530, y: 478 },
  { name: "Panetolikos GFS", country: "Greece", x: 518, y: 471 },
  { name: "OFI Crete FC", country: "Greece", x: 548, y: 500 },
];

// Create a lookup map for quick access
export const hardcodedPositionsMap = new Map<string, HardcodedClubPosition>();
hardcodedClubPositions.forEach((club) => {
  hardcodedPositionsMap.set(club.name, club);
});

// Get hardcoded position for a club by name
export function getHardcodedPosition(clubName: string): { x: number; y: number } | null {
  const club = hardcodedPositionsMap.get(clubName);
  return club ? { x: club.x, y: club.y } : null;
}
