UPDATE public.players
SET email = 'cristiano.ronaldo@risefootballagency.com'
WHERE id = 'e3ae5dcd-0a67-4d49-bf04-879040c4b8c3'
  AND (email IS NULL OR email = '');

INSERT INTO public.translations (page_name, text_key, english) VALUES
  ('representation', 'representation.seo_title', 'Representation | RISE Football Agency'),
  ('representation', 'representation.seo_desc', 'Realise your potential with RISE: proper analysis, real club introductions and clear standards. See exactly what representation looks like for your age and position.'),
  ('representation', 'representation.mission_bio', 'RISE Football Agency is built on a deep understanding of performance and how it shapes decisions at every level of the game. We represent and work directly with players and clubs through an established international network, underpinned by an unrivalled background in developing Premier League level talent. With scouting coverage across Europe informing recruitment and placement through evidence, standards and proven pathways, our stars must share our work ethic, mindset and attention to detail to performance.'),
  ('representation', 'representation.position_breakdown_eyebrow', 'Position breakdown'),
  ('representation', 'representation.scouting_eyebrow', 'How we decide whether there is a fit'),
  ('representation', 'representation.performance_eyebrow', 'Real depth, real Premier League experience'),
  ('representation', 'representation.network_eyebrow', 'Context before contact'),
  ('representation', 'representation.brand_eyebrow', 'Building presence and opportunity'),
  ('representation', 'representation.negotiation_eyebrow', 'Short and long-term deal strategy'),
  ('representation', 'representation.fees_eyebrow', 'A fair industry-standard 5%'),
  ('representation', 'representation.agreement_eyebrow', 'How we sign together, typically 2 years'),
  ('representation', 'representation.expectations_eyebrow', 'A different level of will'),
  ('representation', 'representation.scouting_p1', 'You send the key details, recent footage and enough information for us to assess properly.'),
  ('representation', 'representation.scouting_p2', 'We grade against 16 position-specific attributes across Physical, Mental, Technical and Tactical domains.'),
  ('representation', 'representation.scouting_p3', 'If the fit is there, we look more closely and speak directly about the next step.'),
  ('representation', 'representation.scouting_p4', 'If it is not there yet, that is better said clearly than dressed up with nonsense.'),
  ('representation', 'representation.negotiation_p1', 'We prepare negotiations around the player''s evidence, current value and realistic next step.'),
  ('representation', 'representation.negotiation_p2', 'Short-term terms are handled with care so the immediate deal protects the player properly.'),
  ('representation', 'representation.negotiation_p3', 'Long-term planning matters too, because the wrong clause or pathway can restrict the next move.'),
  ('representation', 'representation.negotiation_p4', 'The aim is simple: better deals, clearer protection and decisions that support the player''s career.'),
  ('representation', 'representation.perf_analysis_title', 'Analysis'),
  ('representation', 'representation.perf_analysis_blurb', 'Full match analysis and opponent breakdowns.'),
  ('representation', 'representation.perf_analysis_d1', 'Full match analysis with chronological context, not just selected highlights.'),
  ('representation', 'representation.perf_analysis_d2', 'Opponent breakdowns highlighting how the game shaped your decisions and outputs.'),
  ('representation', 'representation.perf_analysis_d3', 'Clipped key moments turned into a clear development picture.'),
  ('representation', 'representation.perf_analysis_d4', 'Used both for self-review and to give clubs an honest read of your level.'),
  ('representation', 'representation.perf_actions_title', 'Action Reports'),
  ('representation', 'representation.perf_actions_blurb', 'R90-graded action reports for every meaningful touch.'),
  ('representation', 'representation.perf_actions_d1', 'Every meaningful touch graded with the R90 system.'),
  ('representation', 'representation.perf_actions_d2', 'Each clip carries a score, the surrounding context and the coaching point.'),
  ('representation', 'representation.perf_actions_d3', 'Actions are grouped into categories so themes and trends are easy to read.'),
  ('representation', 'representation.perf_actions_d4', 'See the Cristiano Ronaldo example below for the exact format.'),
  ('representation', 'representation.perf_sps_title', 'Strength, Power & Speed'),
  ('representation', 'representation.perf_sps_blurb', 'Position-specific physical benchmarks and programmes.'),
  ('representation', 'representation.perf_sps_d1', 'Physical benchmarks tied to position-specific demands, not generic gym standards.'),
  ('representation', 'representation.perf_sps_d2', 'Targeted programmes built around your in-game outputs and weak points.'),
  ('representation', 'representation.perf_sps_d3', 'Periodised so the heavy work serves the football, not the other way around.'),
  ('representation', 'representation.perf_sps_d4', 'Reviewed regularly so progress is measured, not assumed.'),
  ('representation', 'representation.perf_nutrition_title', 'Nutrition'),
  ('representation', 'representation.perf_nutrition_blurb', 'Practical fuelling, recovery and hydration guidance.'),
  ('representation', 'representation.perf_nutrition_d1', 'Practical fuelling shaped around training and match weeks.'),
  ('representation', 'representation.perf_nutrition_d2', 'Recovery and hydration guidance that fits real schedules.'),
  ('representation', 'representation.perf_nutrition_d3', 'Nothing faddish, just the work that actually keeps a player available and sharp.'),
  ('representation', 'representation.perf_nutrition_d4', 'Adjusted as workload, environment and goals change.'),
  ('representation', 'representation.perf_technique_title', 'Technique'),
  ('representation', 'representation.perf_technique_blurb', 'Detailed technical reviews on touch, passing and finishing.'),
  ('representation', 'representation.perf_technique_d1', 'Detailed reviews on first touch, passing, finishing and position-specific actions.'),
  ('representation', 'representation.perf_technique_d2', 'Frame-by-frame breakdowns where it matters.'),
  ('representation', 'representation.perf_technique_d3', 'Focus stays on the technical detail clubs notice when they trust a player.'),
  ('representation', 'representation.perf_technique_d4', 'Reinforced with clear, repeatable correction work.'),
  ('representation', 'representation.perf_psychology_title', 'Psychology'),
  ('representation', 'representation.perf_psychology_blurb', 'Mindset, focus and the mental side of competing.'),
  ('representation', 'representation.perf_psychology_d1', 'Mindset, focus and consistency at the level we are pushing towards.'),
  ('representation', 'representation.perf_psychology_d2', 'Honest conversations about pressure, setbacks and standards.'),
  ('representation', 'representation.perf_psychology_d3', 'Tools and frameworks that help on and off the pitch.'),
  ('representation', 'representation.perf_psychology_d4', 'The mental side is treated as part of performance, not an afterthought.'),
  ('representation', 'representation.perf_portal_title', 'Portal'),
  ('representation', 'representation.perf_portal_blurb', 'Your private hub for analysis, reports and direct support.'),
  ('representation', 'representation.perf_portal_d1', 'A bespoke portal for every represented player with reports, analyses and clipped actions in one place.'),
  ('representation', 'representation.perf_portal_d2', 'Direct messaging with the team and a clear record of work shared throughout the season.'),
  ('representation', 'representation.perf_portal_d3', 'Training programmes, schedules and development notes always available on phone or desktop.'),
  ('representation', 'representation.perf_portal_d4', 'Use the live example portal to see exactly what an active player sees.'),
  ('representation', 'representation.whatsapp_intro', 'Hi RISE, I''d like to enquire about representation.'),
  ('representation', 'representation.wa_name', 'Name'),
  ('representation', 'representation.wa_phone', 'Phone'),
  ('representation', 'representation.wa_email', 'Email'),
  ('representation', 'representation.wa_current_club', 'Current club'),
  ('representation', 'representation.wa_dob', 'Date of birth'),
  ('representation', 'representation.wa_position', 'Position'),
  ('representation', 'representation.wa_parent', 'Parent/guardian'),
  ('representation', 'representation.wa_parent_phone', 'Parent/guardian phone'),
  ('representation', 'representation.wa_match_videos', 'Match videos'),
  ('representation', 'representation.wa_notes', 'Notes')
ON CONFLICT (page_name, text_key) DO UPDATE
SET english = EXCLUDED.english,
    updated_at = now();