
-- Insert club_direction translations (English values)
INSERT INTO translations (page_name, text_key, english) VALUES
('club_direction', 'club_direction.badge', 'Strategic Consultancy'),
('club_direction', 'club_direction.hero_title', 'CLUB'),
('club_direction', 'club_direction.hero_highlight', 'DIRECTION'),
('club_direction', 'club_direction.hero_subtitle', 'Strategic consultancy to help clubs compete at the highest level'),
('club_direction', 'club_direction.hero_cta', 'Arrange a Consultation'),
('club_direction', 'club_direction.why_title', 'WHY WORK WITH'),
('club_direction', 'club_direction.why_highlight', 'RISE?'),
('club_direction', 'club_direction.why_desc', 'National exclusivity for our club partners means undivided time and resources for your success.'),
('club_direction', 'club_direction.services_title', 'OUR'),
('club_direction', 'club_direction.services_highlight', 'SERVICES'),
('club_direction', 'club_direction.services_desc', 'Comprehensive support tailored to your club''s specific needs and objectives'),
('club_direction', 'club_direction.svc1_title', 'Strategic Planning'),
('club_direction', 'club_direction.svc1_desc', 'Comprehensive squad planning aligned with your club''s vision and financial parameters.'),
('club_direction', 'club_direction.svc1_f1', 'Short and long-term squad analysis'),
('club_direction', 'club_direction.svc1_f2', 'Budget optimisation'),
('club_direction', 'club_direction.svc1_f3', 'Competitive positioning'),
('club_direction', 'club_direction.svc2_title', 'Talent Identification'),
('club_direction', 'club_direction.svc2_desc', 'Access our European scouting network to find players that fit your specific requirements.'),
('club_direction', 'club_direction.svc2_f1', 'Bespoke player shortlists'),
('club_direction', 'club_direction.svc2_f2', 'Video analysis packages'),
('club_direction', 'club_direction.svc2_f3', 'Background verification'),
('club_direction', 'club_direction.svc3_title', 'Performance Analysis'),
('club_direction', 'club_direction.svc3_desc', 'Data-driven insights to evaluate current squad performance and identify improvement areas.'),
('club_direction', 'club_direction.svc3_f1', 'Individual player reports'),
('club_direction', 'club_direction.svc3_f2', 'Team tactical analysis'),
('club_direction', 'club_direction.svc3_f3', 'Opposition scouting'),
('club_direction', 'club_direction.svc4_title', 'Development Pathways'),
('club_direction', 'club_direction.svc4_desc', 'Structured development programmes for academy and first team integration.'),
('club_direction', 'club_direction.svc4_f1', 'Youth development frameworks'),
('club_direction', 'club_direction.svc4_f2', 'Loan strategy consultation'),
('club_direction', 'club_direction.svc4_f3', 'Progression planning'),
('club_direction', 'club_direction.svc5_title', 'Staff Development'),
('club_direction', 'club_direction.svc5_desc', 'Support for coaching staff development and departmental alignment.'),
('club_direction', 'club_direction.svc5_f1', 'Coaching consultation'),
('club_direction', 'club_direction.svc5_f2', 'Staff structure review'),
('club_direction', 'club_direction.svc5_f3', 'Best practice sharing'),
('club_direction', 'club_direction.svc6_title', 'Market Intelligence'),
('club_direction', 'club_direction.svc6_desc', 'Real-time market insights and player availability across European leagues.'),
('club_direction', 'club_direction.svc6_f1', 'Transfer market updates'),
('club_direction', 'club_direction.svc6_f2', 'Contract situation monitoring'),
('club_direction', 'club_direction.svc6_f3', 'Valuation guidance'),
('club_direction', 'club_direction.results_title', 'PROVEN'),
('club_direction', 'club_direction.results_highlight', 'RESULTS'),
('club_direction', 'club_direction.case1_title', 'Academy Pipeline'),
('club_direction', 'club_direction.case1_desc', 'Professionals developed through our network'),
('club_direction', 'club_direction.case2_title', 'Big 5 Placements'),
('club_direction', 'club_direction.case2_desc', 'Players placed in Europe''s elite leagues'),
('club_direction', 'club_direction.case3_title', 'Transfer Value'),
('club_direction', 'club_direction.case3_desc', 'Combined transfer fees generated'),
('club_direction', 'club_direction.process_title', 'HOW IT'),
('club_direction', 'club_direction.process_highlight', 'WORKS'),
('club_direction', 'club_direction.step1_title', 'Initial Consultation'),
('club_direction', 'club_direction.step1_desc', 'We meet to understand your club''s vision, challenges, and objectives.'),
('club_direction', 'club_direction.step2_title', 'Assessment'),
('club_direction', 'club_direction.step2_desc', 'Comprehensive review of your current setup and requirements.'),
('club_direction', 'club_direction.step3_title', 'Strategy'),
('club_direction', 'club_direction.step3_desc', 'A tailored plan aligned with your goals and budget.'),
('club_direction', 'club_direction.step4_title', 'Implementation'),
('club_direction', 'club_direction.step4_desc', 'Ongoing support and guidance to achieve results.'),
('club_direction', 'club_direction.cta_title', 'READY TO'),
('club_direction', 'club_direction.cta_highlight', 'ELEVATE YOUR CLUB?'),
('club_direction', 'club_direction.cta_desc', 'Let''s discuss how we can help your club achieve its goals'),
('club_direction', 'club_direction.cta_meeting', 'Arrange a Meeting'),
('club_direction', 'club_direction.cta_learn', 'Learn More'),
('club_direction', 'club_direction.bento_strategic', 'Comprehensive squad planning aligned with your vision'),
('club_direction', 'club_direction.stat_connections', 'Club Connections Across Europe'),
('club_direction', 'club_direction.stat_experience', 'Years Combined Experience'),
('club_direction', 'club_direction.bento_analysis', 'Analysis'),
('club_direction', 'club_direction.bento_exclusivity', 'National Exclusivity'),
('club_direction', 'club_direction.bento_exclusivity_desc', 'Undivided attention'),
('club_direction', 'club_direction.bento_network', 'European Network'),
('club_direction', 'club_direction.bento_network_desc', 'Direct relationships with key decision-makers across Europe''s top leagues'),
('club_direction', 'club_direction.bento_data', 'Data-Driven'),
('club_direction', 'club_direction.bento_data_desc', 'Insights across all of Europe'),
('club_direction', 'club_direction.bento_proactive', 'Proactive'),
('club_direction', 'club_direction.bento_proactive_desc', 'Ahead of the curve'),
-- FAQ translations
('faq', 'faq.players.subtitle', 'Common Questions'),
('faq', 'faq.players.title', 'Frequently Asked Questions'),
('faq', 'faq.players.q1', 'How do I get represented by RISE?'),
('faq', 'faq.players.a1', 'We scout players across Europe and beyond. If you believe you have the talent and ambition to compete at a high level, reach out via our contact page or WhatsApp. We''ll arrange a review of your footage and discuss next steps.'),
('faq', 'faq.players.q2', 'What does RISE offer its players?'),
('faq', 'faq.players.a2', 'We provide end-to-end career management including contract negotiation, club placement, performance analysis, personalised coaching programmes, marketing support and more. Every player gets access to our dedicated portal with video analysis, training plans and direct communication with the team.'),
('faq', 'faq.players.q3', 'How does the player portal work?'),
('faq', 'faq.players.a3', 'Each represented player receives login credentials to our bespoke portal. Inside you''ll find match analyses, performance reports, highlight reels, training programmes and direct messaging with your agent. It''s designed to keep you informed and developing at all times.'),
('faq', 'faq.players.q4', 'Can clubs enquire about specific players?'),
('faq', 'faq.players.a4', 'Absolutely. Clubs can declare interest in any player listed on this page, request our full portfolio, or contact us directly. We respond to all professional enquiries within 24 hours.'),
('faq', 'faq.players.q5', 'What level of players does RISE represent?'),
('faq', 'faq.players.a5', 'We work with players across a range of levels, from promising academy graduates to established professionals in Europe''s top divisions. Our network spans multiple countries and leagues, allowing us to find the right fit for every player''s career stage.'),
('faq', 'faq.players.q6', 'Is there a cost to be represented?'),
('faq', 'faq.players.a6', 'Players are never charged upfront fees. Our compensation is structured through industry-standard representation agreements, meaning we only succeed when you succeed.'),
('faq', 'faq.seo_title', 'FAQ - Common Questions | RISE Football Agency'),
('faq', 'faq.seo_desc', 'Find answers to common questions about player representation, our services, the player portal, and working with RISE Football Agency.')
ON CONFLICT DO NOTHING;
