INSERT INTO public.translations
  (page_name, text_key, english, spanish, portuguese, french, german, italian, polish, czech, russian, turkish, croatian, norwegian)
VALUES
  ('representation', 'representation.intro_line1',
    'Realise your potential.',
    'Alcanza tu potencial.',
    'Alcance o seu potencial.',
    'Réalisez votre potentiel.',
    'Erreiche dein Potenzial.',
    'Realizza il tuo potenziale.',
    'Wykorzystaj swój potencjał.',
    'Naplň svůj potenciál.',
    'Раскрой свой потенциал.',
    'Potansiyelini ortaya çıkar.',
    'Ostvari svoj potencijal.',
    'Realiser potensialet ditt.'),
  ('representation', 'representation.intro_line2',
    'See where you are going.',
    'Visualiza hacia dónde vas.',
    'Veja para onde está a ir.',
    'Voyez où vous allez.',
    'Sieh, wohin du gehst.',
    'Vedi dove stai andando.',
    'Zobacz, dokąd zmierzasz.',
    'Vidět, kam směřuješ.',
    'Увидь, куда ты идёшь.',
    'Nereye gittiğini gör.',
    'Vidi kamo ideš.',
    'Se hvor du er på vei.'),
  ('representation', 'representation.intro_line3',
    'Realise your potential.',
    'Alcanza tu potencial.',
    'Alcance o seu potencial.',
    'Réalisez votre potentiel.',
    'Erreiche dein Potenzial.',
    'Realizza il tuo potenziale.',
    'Wykorzystaj swój potencjał.',
    'Naplň svůj potenciál.',
    'Раскрой свой потенциал.',
    'Potansiyelini ortaya çıkar.',
    'Ostvari svoj potencijal.',
    'Realiser potensialet ditt.'),
  ('representation', 'representation.intro_line4',
    'Work with us to make it a reality.',
    'Trabaja con nosotros para hacerlo realidad.',
    'Trabalhe connosco para o tornar realidade.',
    'Travaillez avec nous pour en faire une réalité.',
    'Arbeite mit uns, um es Realität werden zu lassen.',
    'Lavora con noi per renderlo realtà.',
    'Pracuj z nami, aby to urzeczywistnić.',
    'Pracuj s námi, aby se to stalo skutečností.',
    'Работай с нами, чтобы это стало реальностью.',
    'Bunu gerçeğe dönüştürmek için bizimle çalış.',
    'Radi s nama da to postane stvarnost.',
    'Jobb med oss for å gjøre det til virkelighet.'),
  ('representation', 'representation.intro_line5',
    'Then…',
    'Entonces…',
    'Então…',
    'Alors…',
    'Dann…',
    'Allora…',
    'Wtedy…',
    'Pak…',
    'Тогда…',
    'O zaman…',
    'Tada…',
    'Da…'),
  ('representation', 'representation.tap_to_start',
    'Tap anywhere to start',
    'Toca en cualquier sitio para empezar',
    'Toque em qualquer sítio para começar',
    'Touchez n''importe où pour commencer',
    'Tippe irgendwo, um zu starten',
    'Tocca ovunque per iniziare',
    'Dotknij w dowolnym miejscu, aby rozpocząć',
    'Klepněte kamkoli pro start',
    'Нажмите в любом месте, чтобы начать',
    'Başlamak için herhangi bir yere dokunun',
    'Dodirnite bilo gdje za početak',
    'Trykk hvor som helst for å starte'),
  ('representation', 'representation.click_to_start',
    'Click anywhere to start',
    'Haz clic en cualquier sitio para empezar',
    'Clique em qualquer sítio para começar',
    'Cliquez n''importe où pour commencer',
    'Klicke irgendwo, um zu starten',
    'Clicca ovunque per iniziare',
    'Kliknij w dowolnym miejscu, aby rozpocząć',
    'Klikněte kamkoli pro start',
    'Нажмите в любом месте, чтобы начать',
    'Başlamak için herhangi bir yere tıklayın',
    'Kliknite bilo gdje za početak',
    'Klikk hvor som helst for å starte')
ON CONFLICT (page_name, text_key) DO UPDATE SET
  english = EXCLUDED.english,
  spanish = EXCLUDED.spanish,
  portuguese = EXCLUDED.portuguese,
  french = EXCLUDED.french,
  german = EXCLUDED.german,
  italian = EXCLUDED.italian,
  polish = EXCLUDED.polish,
  czech = EXCLUDED.czech,
  russian = EXCLUDED.russian,
  turkish = EXCLUDED.turkish,
  croatian = EXCLUDED.croatian,
  norwegian = EXCLUDED.norwegian;